FIX: Patch Python lower bound on anaconda-client v1.12.0
conda-forge/conda-forge-repodata-patches-feedstock pull request #492
Opened 2023-08-07 22:27 UTC by matthewfeickert

Checklist
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
```
(debug) root@30cca0b0ce64:/debug# python show_diff.py 
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::anaconda-client-1.12.0-pyhd8ed1ab_0.conda
-    "python >=3.6",
-    "python-dateutil >=2.6.1",
+    "python >=3.8",
+    "python >=3.8",
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-armv7l/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-32/repodata.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/win-64/repodata.json.bz2
```
* [x] Modifications won't affect packages built in the future. 
   - This conditions on the build number, not the datetime.

2023-08-07 22:28 UTC, matthewfeickert commented
@jakirkham, @goanpeca, @beckermr as you are listed as being the `anaconda-client` feedstock maintainers please review this.

2023-08-07 22:29 UTC, beckermr commented
The patch appears to remove the python-dateutil dep. Please fix.

2023-08-07 22:29 UTC, beckermr commented on recipe/gen_patch_json.py
> +                python_pinning = [x for x in record["depends"] if x.startswith("python")]
```suggestion
                python_pinning = [x for x in record["depends"] if x.startswith("python ")]
```

2023-08-07 22:30 UTC, beckermr requested changes
I think this will fix it.

2023-08-07 23:14 UTC, beckermr commented
Pls post a new diff. Thank you!

2023-08-07 23:19 UTC, matthewfeickert commented
> I think this will fix it.

Yes, seems so. I'm going to rebase this to avoid noise in the commit history. 

> Pls post a new diff. Thank you!

Still running, as I'm on a slow 4G connection in a remote area currently, but looks correct now:

```console
(debug) root@30cca0b0ce64:/debug# python show_diff.py 
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2
noarch::anaconda-client-1.12.0-pyhd8ed1ab_0.conda
-    "python >=3.6",
+    "python >=3.8",
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata_from_packages.json.bz2
Downloading: https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2
```

2023-08-07 23:27 UTC, jakirkham commented
Tried to re-request a review. Sorry if that wound up being messy

2023-08-07 23:28 UTC, matthewfeickert commented
Yeah, I had already done that. :/

2023-08-07 23:38 UTC, beckermr approved these changes

2023-08-07 23:39 UTC, merged

2023-08-07 23:41 UTC, matthewfeickert commented
Thanks very much @beckermr and @jakirkham.

2023-08-07 23:43 UTC, jakirkham commented
> Yeah, I had already done that. :/ But no worries.

The challenges of using GitHub mobile 😅

Anyways still much improved over what use to be possible

2023-08-07 23:46 UTC, matthewfeickert commented
> The challenges of using GitHub mobile

Haha, 100% feel that. :) I appreciate you just trying to move things along, so thank you very much and thank you for pointing me in the right directions to get this fixed! :pray: 

> Anyways still much improved over what use to be possible

Everytime I make a PR on a plane now from my phone it feels like pure magic. :sparkles:

2023-08-07 23:58 UTC, jakirkham commented
Right back at you :)

Interesting are using GitHub Mobile to create PRs or something else like Working Copy?

2023-08-08 00:00 UTC, matthewfeickert commented
> Interesting are using GitHub Mobile to create PRs or something else like Working Copy?

Just GitHub Mobile + GitHub the website from browser on phone (to check CI). Not great, but possible! I didn't know about Working Copy, but I'll check that out.