Patch openff-bespokefit packages for QCPortal<0.49 following API change
conda-forge/conda-forge-repodata-patches-feedstock pull request #665
Opened 2024-02-13 01:23 UTC by j-wags

Checklist

* [x] Used a static YAML file for the patch if possible ([instructions](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md)).
* [x] Only wrote code directly into `generate_patch_json.py` if absolutely necessary.
* [x] Ran `pre-commit run -a` and ensured all files pass the linting checks.
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

Output of running `python show_diff.py`
```diff
(conda-forge-patching) jw@mba$ python show_diff.py --use-cache             
================================================================================
================================================================================
linux-armv7l
================================================================================
================================================================================
win-32
================================================================================
================================================================================
osx-arm64
================================================================================
================================================================================
linux-ppc64le
================================================================================
================================================================================
linux-aarch64
================================================================================
================================================================================
noarch
noarch::openff-bespokefit-0.1.3-pyhd8ed1ab_2.conda
noarch::openff-bespokefit-0.2.2-pyhd8ed1ab_5.conda
noarch::openff-bespokefit-0.1.3-pyhd8ed1ab_0.conda
noarch::openff-bespokefit-0.2.1-pyhd8ed1ab_0.conda
noarch::openff-bespokefit-0.1.1-pyhd8ed1ab_0.tar.bz2
noarch::openff-bespokefit-0.2.2-pyhd8ed1ab_0.conda
noarch::openff-bespokefit-0.1.0-pyhd8ed1ab_0.tar.bz2
noarch::openff-bespokefit-0.1.2-pyhd8ed1ab_1.tar.bz2
noarch::openff-bespokefit-0.1.2-pyhd8ed1ab_0.tar.bz2
noarch::openff-bespokefit-0.2.2-pyhd8ed1ab_1.conda
noarch::openff-bespokefit-0.1.3-pyhd8ed1ab_3.conda
-    "qcportal >=0.15.6",
+    "qcportal >=0.15.6,<0.49.0a0",
================================================================================
================================================================================
win-64
================================================================================
================================================================================
osx-64
================================================================================
================================================================================
linux-64
```

2024-02-14 19:37 UTC, j-wags commented
@conda-forge-admin ready for review!

2024-02-18 09:37 UTC, xhochy approved these changes

2024-02-18 09:38 UTC, xhochy requested changes

2024-02-18 09:38 UTC, xhochy commented on recipe/patch_yaml/openff-bespokefit-patch.yaml
> +      upper_bound: "0.49"
The upper bound is exclusive.
```suggestion
      upper_bound: "0.50"
```

2024-02-19 19:51 UTC, xhochy approved these changes

2024-02-19 19:51 UTC, merged