remove libignition-* pins
conda-forge/conda-forge-repodata-patches-feedstock pull request #98
Opened 2020-10-31 18:07 UTC by wolfv

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2020-10-31 18:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-10-31 18:09 UTC, beckermr requested changes
Can you explain why? This will help other people understand the PR and whether or not it can be merged.

2020-10-31 18:11 UTC, wolfv commented
yeah we had some discussion with @traversaro for a new gazebo release. it looks like we were too strict with the run_exports in libignition libraries, and they are ABI compatible across major releases. This prevented gazebo 11.2 to build on Windows: https://github.com/conda-forge/gazebo-feedstock/pull/32

Please don't merge just yet, I am waiting for confirmation by @traversaro that this is OK!

2020-10-31 18:12 UTC, beckermr commented
Is there a change we need in the global pinnings to go with this?

2020-10-31 18:20 UTC, wolfv commented
yeah these are not in the global pinnings yet, afaik. we haven't put in the work. but basically they wouldn't have to, since there should not be a global pinning. You can install libignition-math4 and libignition-math6 side-by-side :)

2020-10-31 18:35 UTC, traversaro commented
> Please don't merge just yet, I am waiting for confirmation by @traversaro that this is OK!

That is ok!

2020-10-31 18:41 UTC, traversaro commented
> 
> 
> > Please don't merge just yet, I am waiting for confirmation by @traversaro that this is OK!
> 
> That is ok! A reference on the API/ABI policy for Ignition libraries can be found in https://ignitionrobotics.org/docs/all/roadmap#feature-roadmap and https://ignitionrobotics.org/docs/all/contributing#contributing-code, but I do not know if there is some more "official" statements. fyi @j-rivero

Actually I have some more doubts, see https://github.com/conda-forge/gazebo-feedstock/pull/32#issuecomment-719971837 .

2020-11-01 11:07 UTC, traversaro commented
> 
> 
> > Please don't merge just yet, I am waiting for confirmation by @traversaro that this is OK!
> 
> That is ok! A reference on the API/ABI policy for Ignition libraries can be found in https://ignitionrobotics.org/docs/all/roadmap#feature-roadmap and https://ignitionrobotics.org/docs/all/contributing#contributing-code, but I do not know if there is some more "official" statements. fyi @j-rivero

As I could not find anything on this, I opened an upstream issue in https://github.com/ignitionrobotics/docs/issues/113 .

2020-11-02 09:48 UTC, wolfv commented
@traversaro with these changes, the diff looks like

I am going to add libsdformat to the patching logic as well, sounds good!?

```diff
win-64::gazebo-11.0.0-h2113c14_10.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.5.0",
+    "libignition-fuel-tools4 >=4.1.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-h63f23f5_11.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3 >=3.5.0",
+    "libignition-fuel-tools4 >=4.1.0",
+    "libignition-transport8 >=8.1.0",
win-64::gazebo-11.0.0-h6446b4b_4.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-fuel-tools4 >=4.0.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-ha6688c9_11.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3 >=3.5.0",
+    "libignition-fuel-tools4 >=4.1.0",
+    "libignition-transport8 >=8.1.0",
win-64::gazebo-11.0.0-ha9b5790_7.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-fuel-tools4 >=4.0.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-hb860008_8.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.5.0",
+    "libignition-fuel-tools4 >=4.1.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-hb860008_9.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.5.0",
+    "libignition-fuel-tools4 >=4.1.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-he9e614d_1.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-fuel-tools4 >=4.0.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-he9e614d_2.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-fuel-tools4 >=4.0.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-he9e614d_3.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-fuel-tools4 >=4.0.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-hf1cbe06_5.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-fuel-tools4 >=4.0.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.0.0-hf1cbe06_6.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-fuel-tools4 >=4.0.0",
+    "libignition-transport8 >=8.0.0",
win-64::gazebo-11.1.0-h6cf0b83_0.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-fuel-tools4 >=4.2.1,<4.3.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3 >=3.6.1",
+    "libignition-fuel-tools4 >=4.2.1",
+    "libignition-transport8 >=8.1.0",
win-64::gazebo-11.1.0-hb6cee51_0.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-fuel-tools4 >=4.2.1,<4.3.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3 >=3.6.1",
+    "libignition-fuel-tools4 >=4.2.1",
+    "libignition-transport8 >=8.1.0",
win-64::gazebo-9.11.0-he9e614d_0.tar.bz2
-    "libignition-transport4 >=4.0.0,<4.1.0a0",
+    "libignition-transport4 >=4.0.0",
win-64::gazebo-9.11.0-he9e614d_1.tar.bz2
-    "libignition-transport4 >=4.0.0,<4.1.0a0",
+    "libignition-transport4 >=4.0.0",
win-64::gazebo-9.11.0-he9e614d_2.tar.bz2
-    "libignition-transport4 >=4.0.0,<4.1.0a0",
+    "libignition-transport4 >=4.0.0",
win-64::gazebo-9.11.0-he9e614d_3.tar.bz2
-    "libignition-transport4 >=4.0.0,<4.1.0a0",
+    "libignition-transport4 >=4.0.0",
win-64::gazebo-9.11.0-he9e614d_4.tar.bz2
-    "libignition-transport4 >=4.0.0,<4.1.0a0",
+    "libignition-transport4 >=4.0.0",
win-64::gazebo-9.12.0-he9e614d_0.tar.bz2
-    "libignition-transport4 >=4.0.0,<4.1.0a0",
+    "libignition-transport4 >=4.0.0",
win-64::gazebo-9.12.0-he9e614d_1.tar.bz2
-    "libignition-transport4 >=4.0.0,<4.1.0a0",
+    "libignition-transport4 >=4.0.0",
win-64::libignition-common-3.3.0-h21ff451_0.tar.bz2
-    "libignition-math6 >=6.2.0,<6.3.0a0",
+    "libignition-math6 >=6.2.0",
win-64::libignition-common3-3.3.0-h21ff451_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.4.0-h21ff451_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.4.0-h21ff451_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.4.0-h21ff451_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.4.0-h21ff451_3.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.5.0-h21ff451_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.5.0-h21ff451_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.5.0-h21ff451_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.6.1-h21ff451_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0",
win-64::libignition-common3-3.7.0-h13ae965_1.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6 >=6.6.0",
win-64::libignition-common3-3.7.0-h21ff451_0.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6 >=6.6.0",
win-64::libignition-fuel-tools-4.0.0-hedfdca1_0.tar.bz2
-    "libignition-common3 >=3.3.0,<3.4.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.3.0",
+    "libignition-msgs5 >=5.1.0",
win-64::libignition-fuel-tools4-4.0.0-hedfdca1_0.tar.bz2
-    "libignition-common3 >=3.3.0,<3.4.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.3.0",
+    "libignition-msgs5 >=5.1.0",
win-64::libignition-fuel-tools4-4.0.0-hedfdca1_1.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-msgs5 >=5.1.0",
win-64::libignition-fuel-tools4-4.0.0-hedfdca1_2.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.4.0",
+    "libignition-msgs5 >=5.1.0",
win-64::libignition-fuel-tools4-4.1.0-h85c5bf0_1.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.5.0",
+    "libignition-msgs5 >=5.1.0",
win-64::libignition-fuel-tools4-4.1.0-h85c5bf0_2.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-msgs5 >=5.3.0,<5.4.0a0",
+    "libignit [...]

2020-11-02 10:30 UTC, traversaro commented
> I am going to add libsdformat to the patching logic as well, sounds good!?

Perfect!

2020-11-02 10:49 UTC, Tobias-Fischer commented
Nice, thanks @wolfv!

2020-11-02 10:51 UTC, wolfv commented
actually for libsdformat we need to add a upper bound since we don't publish to seperate package names ... @traversaro should we fix that?

2020-11-02 11:05 UTC, traversaro commented
> actually for libsdformat we need to add a upper bound since we don't publish to seperate package names ... @traversaro should we fix that?

This is a good point, even if since https://github.com/conda-forge/libsdformat-feedstock/pull/16 we will start publishing separate packages, so I don't know if it is worth to fix this for sdformat <= 8 .

2020-11-02 13:26 UTC, wolfv commented
```diff
linux-64::gazebo-11.0.0-h2bf7b13_5.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0,<4",
+    "libignition-fuel-tools4 >=4.0.0,<5",
+    "libignition-transport8 >=8.0.0,<9",
-    "libsdformat >=9.1.0,<9.2.0a0",
+    "libsdformat >=9.1.0,<10",
linux-64::gazebo-11.0.0-h2bf7b13_6.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0,<4",
+    "libignition-fuel-tools4 >=4.0.0,<5",
+    "libignition-transport8 >=8.0.0,<9",
-    "libsdformat >=9.1.0,<9.2.0a0",
+    "libsdformat >=9.1.0,<10",
linux-64::gazebo-11.0.0-h2bf7b13_7.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.4.0,<4",
+    "libignition-fuel-tools4 >=4.0.0,<5",
+    "libignition-transport8 >=8.0.0,<9",
-    "libsdformat >=9.1.0,<9.2.0a0",
+    "libsdformat >=9.1.0,<10",
linux-64::gazebo-11.0.0-h32bde7a_11.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3 >=3.5.0,<4",
+    "libignition-fuel-tools4 >=4.1.0,<5",
+    "libignition-transport8 >=8.1.0,<9",
-    "libsdformat >=9.3.0,<9.4.0a0",
+    "libsdformat >=9.3.0,<10",
linux-64::gazebo-11.0.0-h398b6f7_8.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.5.0,<4",
+    "libignition-fuel-tools4 >=4.1.0,<5",
+    "libignition-transport8 >=8.0.0,<9",
-    "libsdformat >=9.2.0,<9.3.0a0",
+    "libsdformat >=9.2.0,<10",
linux-64::gazebo-11.0.0-h398b6f7_9.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.5.0,<4",
+    "libignition-fuel-tools4 >=4.1.0,<5",
+    "libignition-transport8 >=8.0.0,<9",
-    "libsdformat >=9.2.0,<9.3.0a0",
+    "libsdformat >=9.2.0,<10",
linux-64::gazebo-11.0.0-h83d8fc8_11.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3 >=3.5.0,<4",
+    "libignition-fuel-tools4 >=4.1.0,<5",
+    "libignition-transport8 >=8.1.0,<9",
-    "libsdformat >=9.3.0,<9.4.0a0",
+    "libsdformat >=9.3.0,<10",
linux-64::gazebo-11.0.0-hb54441d_10.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3 >=3.5.0,<4",
+    "libignition-fuel-tools4 >=4.1.0,<5",
+    "libignition-transport8 >=8.0.0,<9",
-    "libsdformat >=9.3.0,<9.4.0a0",
+    "libsdformat >=9.3.0,<10",
linux-64::gazebo-11.1.0-h1c9e8e2_0.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-fuel-tools4 >=4.2.1,<4.3.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3 >=3.6.1,<4",
+    "libignition-fuel-tools4 >=4.2.1,<5",
+    "libignition-transport8 >=8.1.0,<9",
-    "libsdformat >=9.3.0,<9.4.0a0",
+    "libsdformat >=9.3.0,<10",
linux-64::gazebo-11.1.0-hfe1d10a_0.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-fuel-tools4 >=4.2.1,<4.3.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3 >=3.6.1,<4",
+    "libignition-fuel-tools4 >=4.2.1,<5",
+    "libignition-transport8 >=8.1.0,<9",
-    "libsdformat >=9.3.0,<9.4.0a0",
+    "libsdformat >=9.3.0,<10",
linux-64::gazebo-9.15.0-hc15001b_0.tar.bz2
-    "libignition-transport4 >=4.0.0,<4.1.0a0",
+    "libignition-transport4 >=4.0.0,<5",
-    "libsdformat >=6.2.0,<6.3.0a0",
+    "libsdformat >=6.2.0,<7",
linux-64::libignition-common-3.3.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.2.0,<6.3.0a0",
+    "libignition-math6 >=6.2.0,<7",
linux-64::libignition-common3-3.3.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.4.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.4.0-hf10cc52_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.4.0-hf10cc52_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.4.0-hf10cc52_3.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.5.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.5.0-hf10cc52_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.5.0-hf10cc52_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.6.1-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6 >=6.4.0,<7",
linux-64::libignition-common3-3.7.0-h489f4b3_1.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6 >=6.6.0,<7",
linux-64::libignition-common3-3.7.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6 >=6.6.0,<7",
linux-64::libignition-fuel-tools-4.0.0-h693f921_0.tar.bz2
-    "libignition-common3 >=3.3.0,<3.4.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.3.0,<4",
+    "libignition-msgs5 >=5.1.0,<6",
linux-64::libignition-fuel-tools4-4.0.0-h693f921_0.tar.bz2
-    "libignition-common3 >=3.3.0,<3.4.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.3.0,<4",
+    "libignition-msgs5 >=5.1.0,<6",
linux-64::libignition-fuel-tools4-4.0.0-h693f921_1.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.4.0,<4",
+    "libignition-msgs5 >=5.1.0,<6",
linux-64::libignition-fuel-tools4-4.0.0-h693f921_2.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.4.0,<4",
+    "libignition-msgs5 >=5.1.0,<6",
linux-64::libignition-fuel-tools4-4.1.0-h693f921_0.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.4.0,<4",
+    "libignition-msgs5 >=5.1.0,<6",
linux-64::libignition-fuel-tools4-4.1.0-hc81f71f_1.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3 >=3.5.0,<4",
+    "libignition-msgs5 >=5.1.0,<6",
linux-64::libignition-fuel-tools4-4.1.0-hc81f71f_2.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-msgs5 >=5.3.0,<5.4.0a0",
+    "libignition-common3 >=3.5.0,<4",
+    "libignition-msgs5 >=5.3.0,<6",
linux-64::libignition-fuel-tools4-4.2.1-hc057b6c_1.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-msgs5 >=5.3.0,<5.4.0a0",
+    "libignition-common3 >=3.6.1,<4",
+    "libignition-msgs5 >=5.3.0,<6",
linux-64::libignition-fuel-tools4-4.2.1-hc81f71f_0.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-msgs5 >=5.3.0,<5.4.0a0",
+    "libignition-common3 >=3.6.1,<4",
+    "libignition-msgs5 >=5.3.0,<6",
linux-64::libignition-fuel-tools5-5.0.0-hc057b6c_1.tar.bz2
-    "libignition-common3 >=3.7.0,<3.8.0a0",
-    "libignition-msgs6 >=6.0.0,<6.1.0a0",
+    "libignition-common3 >=3.7.0,<4",
+    "libignition-msgs6 >=6.0.0,<7",
linux-64::libignition-math4-4.0.0-he1b5a44_0.tar.bz2
-    "libignition-cmake0 >=0.6.1,<0.7.0a0",
+    "libignition-cmake0 >=0.6.1,<1",
linux-64::libignition-mat [...]

2020-11-02 19:04 UTC, isuruf commented on recipe/gen_patch_json.py
> +                    _change_upper_bound(record, dep_idx, True)
```suggestion
                    _pin_looser(fn, record, dep.split(" ")[0], max_pin="x")
```

2020-11-02 19:10 UTC, wolfv commented
cool, that works! Done

2020-11-02 19:12 UTC, isuruf approved these changes
Looks good to me. @beckermr?

2020-11-04 11:06 UTC, merged